// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AddHwidRequest = {
    hwid?: string | null;
};

export type AddTicketCommentRequest = {
    content?: string | null;
};

export type AddToCartRequest = {
    itemType?: string | null;
    itemId?: string;
    quantity?: number;
    period?: number | null;
};

export type AdminMigrateLicenseRequest = {
    newHwid?: string | null;
    reason?: string | null;
    overrideLimit?: boolean;
};

export type AppUserDto = {
    userId?: string | null;
    email?: string | null;
    roles?: Array<string> | null;
    claims?: Array<Claim> | null;
    city?: string | null;
    phoneNumber?: string | null;
};

export type AppUserDtoPaginatedList = {
    items?: Array<AppUserDto> | null;
    totalCount?: number;
    pageNumber?: number;
    readonly totalPages?: number;
    pageSize?: number;
};

export type AppUserDtoPaginatedListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: AppUserDtoPaginatedList;
    readonly errors?: Array<Error> | null;
};

export type AppUserDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: AppUserDto;
    readonly errors?: Array<Error> | null;
};

export type ApplyPromocodeRequest = {
    promocode?: string | null;
};

export type CartDto = {
    id?: string;
    userId?: string;
    promocode?: string | null;
    calculatedTotal?: number | null;
    items?: Array<CartItemDto> | null;
};

export type CartDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: CartDto;
    readonly errors?: Array<Error> | null;
};

export type CartItemDto = {
    id?: string;
    itemType?: string | null;
    itemId?: string;
    itemName?: string | null;
    quantity?: number;
    unitPrice?: number | null;
    period?: number | null;
};

export type ChangeRoleRequest = {
    role?: string | null;
};

export type Claim = {
    readonly issuer?: string | null;
    readonly originalIssuer?: string | null;
    readonly properties?: {
        [key: string]: string;
    } | null;
    subject?: ClaimsIdentity;
    readonly type?: string | null;
    readonly value?: string | null;
    readonly valueType?: string | null;
};

export type ClaimsIdentity = {
    readonly authenticationType?: string | null;
    readonly isAuthenticated?: boolean;
    actor?: ClaimsIdentity;
    bootstrapContext?: unknown;
    readonly claims?: Array<Claim> | null;
    label?: string | null;
    readonly name?: string | null;
    readonly nameClaimType?: string | null;
    readonly roleClaimType?: string | null;
};

export type CompanyDto = {
    id?: string;
    name?: string | null;
    icon?: string | null;
    tagline?: string | null;
    headline?: string | null;
    description?: string | null;
    order?: number;
    productCount?: number;
};

export type CompanyDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<CompanyDto> | null;
    readonly errors?: Array<Error> | null;
};

export type CompanyDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: CompanyDto;
    readonly errors?: Array<Error> | null;
};

export type CreateChildProductRequest = {
    name?: string | null;
    fullName?: string | null;
    familyId?: string | null;
    description?: string | null;
    miniDescription?: string | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number | null;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    prices?: Array<ProductPriceRequest> | null;
};

export type CreateCompanyCommand = {
    name?: string | null;
    icon?: string | null;
    tagline?: string | null;
    headline?: string | null;
    description?: string | null;
};

export type CreateFamilyCommand = {
    name?: string | null;
};

export type CreateLicenseCommand = {
    userId?: string;
    productId?: string;
    name?: string | null;
    email?: string | null;
    licenseCount?: number;
    migrationLimit?: number;
    expiryDate?: string | null;
    isTrial?: boolean;
    willExpire?: boolean;
    type?: string | null;
};

export type CreateOfferCommand = {
    productId?: string;
    discountType?: DiscountType;
    discountValue?: number;
    startDate?: string | null;
    endDate?: string;
    isActive?: boolean;
};

export type CreatePackageCommand = {
    name?: string | null;
    price?: number;
    description?: string | null;
    miniDescription?: string | null;
    hidden?: boolean;
    comingSoon?: boolean;
    withTaxes?: boolean;
    expiryDate?: string | null;
    items?: Array<CreatePackageItemRequest> | null;
};

export type CreatePackageItemRequest = {
    productId?: string;
    period?: number;
    licenseCount?: number;
    migrationLimit?: number;
};

export type CreateProductCommand = {
    name?: string | null;
    fullName?: string | null;
    familyId?: string;
    description?: string | null;
    miniDescription?: string | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number | null;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    companyId?: string;
    prices?: Array<ProductPriceRequest> | null;
    media?: Array<ProductMediaRequest> | null;
};

export type CreatePromocodeCommand = {
    code?: string | null;
    defaultPriceMultiplier?: number | null;
    fixedDiscount?: number | null;
    constantDiscount?: number | null;
    hidden?: boolean;
    withTaxes?: boolean;
    expiresAt?: string | null;
    maxUses?: number | null;
};

export type CreateRoleRequest = {
    name: string;
};

export type CreateTicketCategoryCommand = {
    name?: string | null;
};

export type CreateTicketRequest = {
    title?: string | null;
    description?: string | null;
    categoryId?: string | null;
    priority?: string | null;
};

export type DailyRevenueDto = {
    day?: number;
    date?: string | null;
    totalRevenue?: number;
};

export type DashboardChartDto = {
    year?: number;
    month?: number;
    totalMonthlyRevenue?: number;
    dailyRevenues?: Array<DailyRevenueDto> | null;
};

export type DashboardChartDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: DashboardChartDto;
    readonly errors?: Array<Error> | null;
};

export type DashboardStatsDto = {
    totalProducts?: number;
    totalActiveLicenses?: number;
    totalRevenue?: number;
    totalTickets?: number;
    pendingTickets?: number;
};

export type DashboardStatsDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: DashboardStatsDto;
    readonly errors?: Array<Error> | null;
};

export type Deleted = {
    [key: string]: never;
};

export type DeletedResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: Deleted;
    readonly errors?: Array<Error> | null;
};

export type DiscountType = 0 | 1;

export type Error = {
    readonly code?: string | null;
    readonly description?: string | null;
    type?: ErrorKind;
};

export type ErrorKind = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type FamilyDto = {
    id?: string;
    name?: string | null;
    order?: number;
    productCount?: number;
};

export type FamilyDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<FamilyDto> | null;
    readonly errors?: Array<Error> | null;
};

export type FamilyDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: FamilyDto;
    readonly errors?: Array<Error> | null;
};

export type GetLicenseDiagnosticResponse = {
    id?: string;
    serial?: string | null;
    janDrozdId?: string | null;
    provider?: string | null;
    isActive?: boolean;
    willExpire?: boolean;
    expiryDate?: string | null;
    licenseCount?: number;
    migrationLimit?: number;
    isTrial?: boolean;
    type?: string | null;
    version?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
    customer?: unknown;
    product?: unknown;
    hardwareIds?: unknown;
    stats?: unknown;
};

export type GetLicenseDiagnosticResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: GetLicenseDiagnosticResponse;
    readonly errors?: Array<Error> | null;
};

export type GetLicenseHwidsResponse = {
    hwids?: Array<string> | null;
    source?: string | null;
    customerId?: string | null;
};

export type GetLicenseHwidsResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: GetLicenseHwidsResponse;
    readonly errors?: Array<Error> | null;
};

export type GoogleLoginRequest = {
    idToken?: string | null;
};

export type GuidResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: string;
    readonly errors?: Array<Error> | null;
};

export type LicenseClientDto = {
    id?: string;
    userId?: string;
    productId?: string;
    hwid?: string | null;
    deviceName?: string | null;
    lastUsedAt?: string | null;
    resetCount?: number;
    lastResetAt?: string | null;
    isActive?: boolean;
};

export type LicenseDto = {
    id?: string;
    userId?: string;
    productId?: string;
    paymentId?: string | null;
    pendingLicenseId?: string | null;
    licenseCount?: number;
    migrationLimit?: number;
    name?: string | null;
    email?: string | null;
    hwidSalt?: string | null;
    willExpire?: boolean;
    expiryDate?: string | null;
    serial?: string | null;
    janDrozdId?: string | null;
    isTrial?: boolean;
    type?: string | null;
    version?: string | null;
    addedBy?: string | null;
    addedByName?: string | null;
    productName?: string | null;
    isActive?: boolean;
    source?: string | null;
    provider?: string | null;
    createdAtUtc?: string;
    isExpired?: boolean;
    clients?: Array<LicenseClientDto> | null;
};

export type LicenseDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<LicenseDto> | null;
    readonly errors?: Array<Error> | null;
};

export type LicenseDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: LicenseDto;
    readonly errors?: Array<Error> | null;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type ObjectResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: unknown;
    readonly errors?: Array<Error> | null;
};

export type OfferDto = {
    id?: string;
    productId?: string;
    discountType?: DiscountType;
    discountValue?: number;
    startDate?: string | null;
    endDate?: string;
    isActive?: boolean;
    appliedPrices?: Array<PayablePriceDto> | null;
};

export type OfferDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<OfferDto> | null;
    readonly errors?: Array<Error> | null;
};

export type OfferDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: OfferDto;
    readonly errors?: Array<Error> | null;
};

export type PackageDto = {
    id?: string;
    name?: string | null;
    description?: string | null;
    miniDescription?: string | null;
    imageUrl?: string | null;
    price?: number;
    hidden?: boolean;
    comingSoon?: boolean;
    withTaxes?: boolean;
    expiryDate?: string | null;
    order?: number;
    createdAtUtc?: string;
    lastModifiedUtc?: string;
    items?: Array<PackageItemDto> | null;
};

export type PackageDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<PackageDto> | null;
    readonly errors?: Array<Error> | null;
};

export type PackageDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PackageDto;
    readonly errors?: Array<Error> | null;
};

export type PackageItemDto = {
    id?: string;
    itemType?: string | null;
    itemId?: string;
    itemName?: string | null;
    period?: number;
    licenseCount?: number;
    migrationLimit?: number;
};

export type PayablePriceDto = {
    id?: string;
    country?: string | null;
    price?: number;
    originalPrice?: number | null;
    period?: number | null;
    periodType?: PeriodType;
    active?: boolean;
};

export type PaymentBillingData = {
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    apartment?: string | null;
    floor?: string | null;
    street?: string | null;
    building?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    postalCode?: string | null;
};

export type PaymentCheckoutSessionRequest = {
    resourceId: string;
    referenceCode?: string | null;
    provider?: string | null;
    method?: string | null;
    amountInMinorUnits?: number;
    currency: string;
    paymentMethodIntegrationIds?: Array<number> | null;
    billingData: PaymentBillingData;
    items?: Array<PaymentItem> | null;
    notificationUrl?: string | null;
    redirectionUrl?: string | null;
    extras?: {
        [key: string]: string;
    } | null;
};

export type PaymentCheckoutStartResponse = {
    paymentId?: string;
    intentionId?: string | null;
    clientSecret?: string | null;
    publicKey?: string | null;
    paymentPageUrl?: string | null;
};

export type PaymentCheckoutStartResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PaymentCheckoutStartResponse;
    readonly errors?: Array<Error> | null;
};

export type PaymentItem = {
    name?: string | null;
    description?: string | null;
    amountInMinorUnits?: number;
    quantity?: number;
};

export type PaymentStatusDto = {
    paymentId?: string;
    status?: string | null;
    confirmed?: boolean;
    licenseSerials?: Array<string> | null;
};

export type PaymentStatusDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PaymentStatusDto;
    readonly errors?: Array<Error> | null;
};

export type PaymentWebhookParseResult = {
    isValid?: boolean;
    referenceCode?: string | null;
    externalTransactionId?: string | null;
    isSuccessfulPayment?: boolean;
    isFailure?: boolean;
    failureReason?: string | null;
    eventType?: string | null;
};

export type PaymentWebhookParseResultResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PaymentWebhookParseResult;
    readonly errors?: Array<Error> | null;
};

export type PeriodType = 'Day' | 'Month' | 'Year';

export type ProductDto = {
    id?: string;
    name?: string | null;
    fullName?: string | null;
    description?: string | null;
    miniDescription?: string | null;
    family?: string | null;
    familyId?: string;
    parentProductId?: string | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    company?: string | null;
    companyId?: string;
    createdAtUtc?: string;
    createdBy?: string | null;
    lastModifiedUtc?: string;
    lastModifiedBy?: string | null;
    prices?: Array<PayablePriceDto> | null;
    children?: Array<ProductDto> | null;
    media?: Array<ProductMediaDto> | null;
    features?: Array<ProductFeatureDto> | null;
    startingPrice?: number | null;
    startingPeriod?: number | null;
    startingPeriodType?: PeriodType;
};

export type ProductDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<ProductDto> | null;
    readonly errors?: Array<Error> | null;
};

export type ProductDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: ProductDto;
    readonly errors?: Array<Error> | null;
};

export type ProductFeatureDto = {
    id?: string;
    productId?: string;
    featureName?: string | null;
    featureType?: string | null;
    janDrozdFeatureId?: string | null;
    createdAtUtc?: string;
    createdBy?: string | null;
    lastModifiedUtc?: string;
    lastModifiedBy?: string | null;
};

export type ProductFeatureDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: ProductFeatureDto;
    readonly errors?: Array<Error> | null;
};

export type ProductFeatureRequest = {
    featureName?: string | null;
    featureType?: string | null;
    janDrozdFeatureId?: string | null;
};

export type ProductMediaDto = {
    id?: string;
    productId?: string;
    url?: string | null;
    order?: number;
};

export type ProductMediaDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<ProductMediaDto> | null;
    readonly errors?: Array<Error> | null;
};

export type ProductMediaDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: ProductMediaDto;
    readonly errors?: Array<Error> | null;
};

export type ProductMediaRequest = {
    url?: string | null;
    order?: number;
};

export type ProductPriceRequest = {
    country?: string | null;
    price?: number;
    period?: number | null;
    periodType?: PeriodType;
    active?: boolean;
    id?: string | null;
};

export type ProductVersionDto = {
    id?: string;
    productId?: string;
    versionNumber?: string | null;
    filePath?: string | null;
    fileSizeBytes?: number;
    isActive?: boolean;
    releaseNotes?: string | null;
    createdAtUtc?: string;
};

export type ProductVersionDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<ProductVersionDto> | null;
    readonly errors?: Array<Error> | null;
};

export type ProductVersionDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: ProductVersionDto;
    readonly errors?: Array<Error> | null;
};

export type PromocodeDto = {
    id?: string;
    code?: string | null;
    defaultPriceMultiplier?: number | null;
    fixedDiscount?: number | null;
    constantDiscount?: number | null;
    hidden?: boolean;
    withTaxes?: boolean;
    expiresAt?: string | null;
    maxUses?: number | null;
    useCount?: number;
    isActive?: boolean;
};

export type PromocodeDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<PromocodeDto> | null;
    readonly errors?: Array<Error> | null;
};

export type PromocodeDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: PromocodeDto;
    readonly errors?: Array<Error> | null;
};

export type RefreshTokenRequest = {
    accessToken: string;
    refreshToken: string;
};

export type RegisterUserRequest = {
    email: string;
    password: string;
    role: string;
    city?: string | null;
    phoneNumber?: string | null;
};

export type RenewLicenseRequest = {
    period?: number;
};

export type ReorderCompaniesCommand = {
    companyIds?: Array<string> | null;
};

export type ReorderFamiliesCommand = {
    familyIds?: Array<string> | null;
};

export type ReorderPackagesCommand = {
    packageIds?: Array<string> | null;
};

export type ReorderProductsCommand = {
    parentProductId?: string | null;
    productIds?: Array<string> | null;
};

export type RequestStudentUpgradeRequest = {
    email?: string | null;
};

export type ResetLicenseHwidRequest = {
    reason?: string | null;
};

export type RestoreDeletedUserRequest = {
    email: string;
    password: string;
};

export type RoleDto = {
    id?: string | null;
    name?: string | null;
};

export type RoleDtoListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<RoleDto> | null;
    readonly errors?: Array<Error> | null;
};

export type RoleDtoResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: RoleDto;
    readonly errors?: Array<Error> | null;
};

export type SetPackageHiddenRequest = {
    hidden?: boolean;
};

export type StringIReadOnlyCollectionResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<string> | null;
    readonly errors?: Array<Error> | null;
};

export type StringListResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: Array<string> | null;
    readonly errors?: Array<Error> | null;
};

export type StringResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    readonly value?: string | null;
    readonly errors?: Array<Error> | null;
};

export type TicketCategoryDto = {
    id?: string;
    name?: string | null;
    description?: string | null;
    order?: number;
    isActive?: boolean;
};

export type TokenResponse = {
    accessToken?: string | null;
    refreshToken?: string | null;
    expiresOnUtc?: string;
};

export type TokenResponseResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: TokenResponse;
    readonly errors?: Array<Error> | null;
};

export type UpdateCompanyRequest = {
    name?: string | null;
    icon?: string | null;
    tagline?: string | null;
    headline?: string | null;
    description?: string | null;
};

export type UpdateFamilyRequest = {
    name?: string | null;
};

export type UpdateLicenseCommand = {
    id?: string;
    licenseCount?: number;
    migrationLimit?: number;
    expiryDate?: string | null;
    isTrial?: boolean;
    isActive?: boolean;
    serial?: string | null;
    janDrozdId?: string | null;
};

export type UpdateOfferCommand = {
    id?: string;
    discountType?: DiscountType;
    discountValue?: number;
    startDate?: string | null;
    endDate?: string;
    isActive?: boolean;
};

export type UpdatePackageRequest = {
    name?: string | null;
    price?: number;
    description?: string | null;
    miniDescription?: string | null;
    hidden?: boolean;
    comingSoon?: boolean;
    withTaxes?: boolean;
    expiryDate?: string | null;
    items?: Array<CreatePackageItemRequest> | null;
};

export type UpdateProductCommand = {
    id?: string;
    name?: string | null;
    fullName?: string | null;
    familyId?: string;
    description?: string | null;
    miniDescription?: string | null;
    parentProductId?: string | null;
    comingSoon?: boolean;
    hidden?: boolean;
    order?: number | null;
    withTaxes?: boolean;
    version?: string | null;
    janDrozdId?: string | null;
    companyId?: string;
    prices?: Array<ProductPriceRequest> | null;
    media?: Array<ProductMediaRequest> | null;
};

export type UpdatePromocodeCommand = {
    id?: string;
    defaultPriceMultiplier?: number | null;
    fixedDiscount?: number | null;
    constantDiscount?: number | null;
    hidden?: boolean;
    withTaxes?: boolean;
    expiresAt?: string | null;
    maxUses?: number | null;
};

export type UpdateRoleRequest = {
    name: string;
};

export type UpdateTicketCategoryCommand = {
    id?: string;
    name?: string | null;
    description?: string | null;
    order?: number;
    isActive?: boolean;
};

export type UpdateTicketStatusRequest = {
    status?: string | null;
};

export type Updated = {
    [key: string]: never;
};

export type UpdatedResult = {
    readonly isSuccess?: boolean;
    readonly isError?: boolean;
    value?: Updated;
    readonly errors?: Array<Error> | null;
};

export type VerifyStudentUpgradeRequest = {
    otpCode?: string | null;
};

export type AppUserDtoWritable = {
    userId?: string | null;
    email?: string | null;
    roles?: Array<string> | null;
    claims?: Array<ClaimWritable> | null;
    city?: string | null;
    phoneNumber?: string | null;
};

export type AppUserDtoPaginatedListWritable = {
    items?: Array<AppUserDtoWritable> | null;
    totalCount?: number;
    pageNumber?: number;
    pageSize?: number;
};

export type AppUserDtoPaginatedListResultWritable = {
    value?: AppUserDtoPaginatedListWritable;
};

export type AppUserDtoResultWritable = {
    value?: AppUserDtoWritable;
};

export type CartDtoResultWritable = {
    value?: CartDto;
};

export type ClaimWritable = {
    subject?: ClaimsIdentityWritable;
};

export type ClaimsIdentityWritable = {
    actor?: ClaimsIdentityWritable;
    bootstrapContext?: unknown;
    label?: string | null;
};

export type CompanyDtoListResultWritable = {
    [key: string]: never;
};

export type CompanyDtoResultWritable = {
    value?: CompanyDto;
};

export type DashboardChartDtoResultWritable = {
    value?: DashboardChartDto;
};

export type DashboardStatsDtoResultWritable = {
    value?: DashboardStatsDto;
};

export type DeletedResultWritable = {
    value?: Deleted;
};

export type ErrorWritable = {
    type?: ErrorKind;
};

export type FamilyDtoListResultWritable = {
    [key: string]: never;
};

export type FamilyDtoResultWritable = {
    value?: FamilyDto;
};

export type GetLicenseDiagnosticResponseResultWritable = {
    value?: GetLicenseDiagnosticResponse;
};

export type GetLicenseHwidsResponseResultWritable = {
    value?: GetLicenseHwidsResponse;
};

export type GuidResultWritable = {
    [key: string]: never;
};

export type LicenseDtoListResultWritable = {
    [key: string]: never;
};

export type LicenseDtoResultWritable = {
    value?: LicenseDto;
};

export type ObjectResultWritable = {
    [key: string]: never;
};

export type OfferDtoListResultWritable = {
    [key: string]: never;
};

export type OfferDtoResultWritable = {
    value?: OfferDto;
};

export type PackageDtoListResultWritable = {
    [key: string]: never;
};

export type PackageDtoResultWritable = {
    value?: PackageDto;
};

export type PaymentCheckoutStartResponseResultWritable = {
    value?: PaymentCheckoutStartResponse;
};

export type PaymentStatusDtoResultWritable = {
    value?: PaymentStatusDto;
};

export type PaymentWebhookParseResultResultWritable = {
    value?: PaymentWebhookParseResult;
};

export type ProductDtoListResultWritable = {
    [key: string]: never;
};

export type ProductDtoResultWritable = {
    value?: ProductDto;
};

export type ProductFeatureDtoResultWritable = {
    value?: ProductFeatureDto;
};

export type ProductMediaDtoListResultWritable = {
    [key: string]: never;
};

export type ProductMediaDtoResultWritable = {
    value?: ProductMediaDto;
};

export type ProductVersionDtoListResultWritable = {
    [key: string]: never;
};

export type ProductVersionDtoResultWritable = {
    value?: ProductVersionDto;
};

export type PromocodeDtoListResultWritable = {
    [key: string]: never;
};

export type PromocodeDtoResultWritable = {
    value?: PromocodeDto;
};

export type RoleDtoListResultWritable = {
    [key: string]: never;
};

export type RoleDtoResultWritable = {
    value?: RoleDto;
};

export type StringIReadOnlyCollectionResultWritable = {
    [key: string]: never;
};

export type StringListResultWritable = {
    [key: string]: never;
};

export type StringResultWritable = {
    [key: string]: never;
};

export type TokenResponseResultWritable = {
    value?: TokenResponse;
};

export type UpdatedResultWritable = {
    value?: Updated;
};

export type PostIdentitySignupData = {
    /**
     * The registration details (email, password, etc.).
     */
    body?: RegisterUserRequest;
    path?: never;
    query?: never;
    url: '/identity/signup';
};

export type PostIdentitySignupErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PostIdentitySignupError = PostIdentitySignupErrors[keyof PostIdentitySignupErrors];

export type PostIdentitySignupResponses = {
    /**
     * Created
     */
    201: TokenResponseResult;
};

export type PostIdentitySignupResponse = PostIdentitySignupResponses[keyof PostIdentitySignupResponses];

export type PostIdentityTokenGenerateData = {
    /**
     * The login credentials.
     */
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/identity/token/generate';
};

export type PostIdentityTokenGenerateErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityTokenGenerateError = PostIdentityTokenGenerateErrors[keyof PostIdentityTokenGenerateErrors];

export type PostIdentityTokenGenerateResponses = {
    /**
     * OK
     */
    200: TokenResponseResult;
};

export type PostIdentityTokenGenerateResponse = PostIdentityTokenGenerateResponses[keyof PostIdentityTokenGenerateResponses];

export type PostIdentityTokenGoogleData = {
    /**
     * The Google login credentials containing the IdToken.
     */
    body?: GoogleLoginRequest;
    path?: never;
    query?: never;
    url: '/identity/token/google';
};

export type PostIdentityTokenGoogleErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityTokenGoogleError = PostIdentityTokenGoogleErrors[keyof PostIdentityTokenGoogleErrors];

export type PostIdentityTokenGoogleResponses = {
    /**
     * OK
     */
    200: TokenResponseResult;
};

export type PostIdentityTokenGoogleResponse = PostIdentityTokenGoogleResponses[keyof PostIdentityTokenGoogleResponses];

export type PostIdentityTokenRefreshTokenData = {
    /**
     * The access and refresh tokens.
     */
    body?: RefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/identity/token/refresh-token';
};

export type PostIdentityTokenRefreshTokenErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityTokenRefreshTokenError = PostIdentityTokenRefreshTokenErrors[keyof PostIdentityTokenRefreshTokenErrors];

export type PostIdentityTokenRefreshTokenResponses = {
    /**
     * OK
     */
    200: TokenResponseResult;
};

export type PostIdentityTokenRefreshTokenResponse = PostIdentityTokenRefreshTokenResponses[keyof PostIdentityTokenRefreshTokenResponses];

export type PostIdentityRestoreDeletedUserData = {
    /**
     * The email and password of the user to restore.
     */
    body?: RestoreDeletedUserRequest;
    path?: never;
    query?: never;
    url: '/identity/restore-deleted-user';
};

export type PostIdentityRestoreDeletedUserErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityRestoreDeletedUserError = PostIdentityRestoreDeletedUserErrors[keyof PostIdentityRestoreDeletedUserErrors];

export type PostIdentityRestoreDeletedUserResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PostIdentityRestoreDeletedUserResponse = PostIdentityRestoreDeletedUserResponses[keyof PostIdentityRestoreDeletedUserResponses];

export type PutIdentityUsersByUserIdRoleData = {
    /**
     * The role to assign.
     */
    body?: ChangeRoleRequest;
    path: {
        /**
         * The unique identifier of the user.
         */
        userId: string;
    };
    query?: never;
    url: '/identity/users/{userId}/role';
};

export type PutIdentityUsersByUserIdRoleErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutIdentityUsersByUserIdRoleError = PutIdentityUsersByUserIdRoleErrors[keyof PutIdentityUsersByUserIdRoleErrors];

export type PutIdentityUsersByUserIdRoleResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutIdentityUsersByUserIdRoleResponse = PutIdentityUsersByUserIdRoleResponses[keyof PutIdentityUsersByUserIdRoleResponses];

export type PutIdentityUsersByUserIdRestoreData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user to restore.
         */
        userId: string;
    };
    query?: never;
    url: '/identity/users/{userId}/restore';
};

export type PutIdentityUsersByUserIdRestoreErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutIdentityUsersByUserIdRestoreError = PutIdentityUsersByUserIdRestoreErrors[keyof PutIdentityUsersByUserIdRestoreErrors];

export type PutIdentityUsersByUserIdRestoreResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutIdentityUsersByUserIdRestoreResponse = PutIdentityUsersByUserIdRestoreResponses[keyof PutIdentityUsersByUserIdRestoreResponses];

export type GetIdentityUsersByUserIdPermissionsData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user.
         */
        userId: string;
    };
    query?: never;
    url: '/identity/users/{userId}/permissions';
};

export type GetIdentityUsersByUserIdPermissionsErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetIdentityUsersByUserIdPermissionsError = GetIdentityUsersByUserIdPermissionsErrors[keyof GetIdentityUsersByUserIdPermissionsErrors];

export type GetIdentityUsersByUserIdPermissionsResponses = {
    /**
     * OK
     */
    200: StringListResult;
};

export type GetIdentityUsersByUserIdPermissionsResponse = GetIdentityUsersByUserIdPermissionsResponses[keyof GetIdentityUsersByUserIdPermissionsResponses];

export type PutIdentityUsersByUserIdPermissionsData = {
    body?: Array<string>;
    path: {
        userId: string;
    };
    query?: never;
    url: '/identity/users/{userId}/permissions';
};

export type PutIdentityUsersByUserIdPermissionsErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutIdentityUsersByUserIdPermissionsError = PutIdentityUsersByUserIdPermissionsErrors[keyof PutIdentityUsersByUserIdPermissionsErrors];

export type PutIdentityUsersByUserIdPermissionsResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutIdentityUsersByUserIdPermissionsResponse = PutIdentityUsersByUserIdPermissionsResponses[keyof PutIdentityUsersByUserIdPermissionsResponses];

export type GetIdentityMyPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/my-permissions';
};

export type GetIdentityMyPermissionsErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type GetIdentityMyPermissionsError = GetIdentityMyPermissionsErrors[keyof GetIdentityMyPermissionsErrors];

export type GetIdentityMyPermissionsResponses = {
    /**
     * OK
     */
    200: StringListResult;
};

export type GetIdentityMyPermissionsResponse = GetIdentityMyPermissionsResponses[keyof GetIdentityMyPermissionsResponses];

export type GetIdentityAllPermissionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/all-permissions';
};

export type GetIdentityAllPermissionsErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetIdentityAllPermissionsError = GetIdentityAllPermissionsErrors[keyof GetIdentityAllPermissionsErrors];

export type GetIdentityAllPermissionsResponses = {
    /**
     * OK
     */
    200: StringIReadOnlyCollectionResult;
};

export type GetIdentityAllPermissionsResponse = GetIdentityAllPermissionsResponses[keyof GetIdentityAllPermissionsResponses];

export type DeleteIdentityCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/current-user';
};

export type DeleteIdentityCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type DeleteIdentityCurrentUserError = DeleteIdentityCurrentUserErrors[keyof DeleteIdentityCurrentUserErrors];

export type DeleteIdentityCurrentUserResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteIdentityCurrentUserResponse = DeleteIdentityCurrentUserResponses[keyof DeleteIdentityCurrentUserResponses];

export type GetIdentityCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/current-user';
};

export type GetIdentityCurrentUserErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type GetIdentityCurrentUserError = GetIdentityCurrentUserErrors[keyof GetIdentityCurrentUserErrors];

export type GetIdentityCurrentUserResponses = {
    /**
     * OK
     */
    200: AppUserDtoResult;
};

export type GetIdentityCurrentUserResponse = GetIdentityCurrentUserResponses[keyof GetIdentityCurrentUserResponses];

export type GetIdentityUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The page number.
         */
        pageNumber?: number;
        /**
         * The number of items per page.
         */
        pageSize?: number;
    };
    url: '/identity/users';
};

export type GetIdentityUsersErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetIdentityUsersError = GetIdentityUsersErrors[keyof GetIdentityUsersErrors];

export type GetIdentityUsersResponses = {
    /**
     * OK
     */
    200: AppUserDtoPaginatedListResult;
};

export type GetIdentityUsersResponse = GetIdentityUsersResponses[keyof GetIdentityUsersResponses];

export type GetIdentityUsersDeletedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The page number.
         */
        pageNumber?: number;
        /**
         * The number of items per page.
         */
        pageSize?: number;
    };
    url: '/identity/users/deleted';
};

export type GetIdentityUsersDeletedErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetIdentityUsersDeletedError = GetIdentityUsersDeletedErrors[keyof GetIdentityUsersDeletedErrors];

export type GetIdentityUsersDeletedResponses = {
    /**
     * OK
     */
    200: AppUserDtoPaginatedListResult;
};

export type GetIdentityUsersDeletedResponse = GetIdentityUsersDeletedResponses[keyof GetIdentityUsersDeletedResponses];

export type DeleteIdentityByUserIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the user.
         */
        userId: string;
    };
    query?: never;
    url: '/identity/{userId}';
};

export type DeleteIdentityByUserIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type DeleteIdentityByUserIdError = DeleteIdentityByUserIdErrors[keyof DeleteIdentityByUserIdErrors];

export type DeleteIdentityByUserIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteIdentityByUserIdResponse = DeleteIdentityByUserIdResponses[keyof DeleteIdentityByUserIdResponses];

export type PostIdentityStudentUpgradeRequestData = {
    /**
     * The request containing the university email.
     */
    body?: RequestStudentUpgradeRequest;
    path?: never;
    query?: never;
    url: '/identity/student-upgrade/request';
};

export type PostIdentityStudentUpgradeRequestErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PostIdentityStudentUpgradeRequestError = PostIdentityStudentUpgradeRequestErrors[keyof PostIdentityStudentUpgradeRequestErrors];

export type PostIdentityStudentUpgradeRequestResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PostIdentityStudentUpgradeRequestResponse = PostIdentityStudentUpgradeRequestResponses[keyof PostIdentityStudentUpgradeRequestResponses];

export type PostIdentityStudentUpgradeVerifyData = {
    /**
     * The OTP code.
     */
    body?: VerifyStudentUpgradeRequest;
    path?: never;
    query?: never;
    url: '/identity/student-upgrade/verify';
};

export type PostIdentityStudentUpgradeVerifyErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
};

export type PostIdentityStudentUpgradeVerifyError = PostIdentityStudentUpgradeVerifyErrors[keyof PostIdentityStudentUpgradeVerifyErrors];

export type PostIdentityStudentUpgradeVerifyResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PostIdentityStudentUpgradeVerifyResponse = PostIdentityStudentUpgradeVerifyResponses[keyof PostIdentityStudentUpgradeVerifyResponses];

export type GetIdentityRolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/identity/roles';
};

export type GetIdentityRolesErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetIdentityRolesError = GetIdentityRolesErrors[keyof GetIdentityRolesErrors];

export type GetIdentityRolesResponses = {
    /**
     * OK
     */
    200: RoleDtoListResult;
};

export type GetIdentityRolesResponse = GetIdentityRolesResponses[keyof GetIdentityRolesResponses];

export type PostIdentityRolesData = {
    /**
     * The role details.
     */
    body?: CreateRoleRequest;
    path?: never;
    query?: never;
    url: '/identity/roles';
};

export type PostIdentityRolesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PostIdentityRolesError = PostIdentityRolesErrors[keyof PostIdentityRolesErrors];

export type PostIdentityRolesResponses = {
    /**
     * Created
     */
    201: RoleDtoResult;
};

export type PostIdentityRolesResponse = PostIdentityRolesResponses[keyof PostIdentityRolesResponses];

export type DeleteIdentityRolesByRoleIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the role.
         */
        roleId: string;
    };
    query?: never;
    url: '/identity/roles/{roleId}';
};

export type DeleteIdentityRolesByRoleIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type DeleteIdentityRolesByRoleIdError = DeleteIdentityRolesByRoleIdErrors[keyof DeleteIdentityRolesByRoleIdErrors];

export type DeleteIdentityRolesByRoleIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteIdentityRolesByRoleIdResponse = DeleteIdentityRolesByRoleIdResponses[keyof DeleteIdentityRolesByRoleIdResponses];

export type PutIdentityRolesByRoleIdData = {
    /**
     * The role details to update.
     */
    body?: UpdateRoleRequest;
    path: {
        /**
         * The unique identifier of the role.
         */
        roleId: string;
    };
    query?: never;
    url: '/identity/roles/{roleId}';
};

export type PutIdentityRolesByRoleIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PutIdentityRolesByRoleIdError = PutIdentityRolesByRoleIdErrors[keyof PutIdentityRolesByRoleIdErrors];

export type PutIdentityRolesByRoleIdResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutIdentityRolesByRoleIdResponse = PutIdentityRolesByRoleIdResponses[keyof PutIdentityRolesByRoleIdResponses];

export type DeleteApiV1CartsMyCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/carts/my-cart';
};

export type DeleteApiV1CartsMyCartResponses = {
    /**
     * OK
     */
    200: GuidResult;
};

export type DeleteApiV1CartsMyCartResponse = DeleteApiV1CartsMyCartResponses[keyof DeleteApiV1CartsMyCartResponses];

export type GetApiV1CartsMyCartData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/carts/my-cart';
};

export type GetApiV1CartsMyCartResponses = {
    /**
     * OK
     */
    200: CartDtoResult;
};

export type GetApiV1CartsMyCartResponse = GetApiV1CartsMyCartResponses[keyof GetApiV1CartsMyCartResponses];

export type PostApiV1CartsMyCartItemsData = {
    body?: AddToCartRequest;
    path?: never;
    query?: never;
    url: '/api/v1/carts/my-cart/items';
};

export type PostApiV1CartsMyCartItemsResponses = {
    /**
     * OK
     */
    200: GuidResult;
};

export type PostApiV1CartsMyCartItemsResponse = PostApiV1CartsMyCartItemsResponses[keyof PostApiV1CartsMyCartItemsResponses];

export type DeleteApiV1CartsMyCartItemsByItemIdData = {
    body?: never;
    path: {
        itemId: string;
    };
    query?: never;
    url: '/api/v1/carts/my-cart/items/{itemId}';
};

export type DeleteApiV1CartsMyCartItemsByItemIdResponses = {
    /**
     * OK
     */
    200: GuidResult;
};

export type DeleteApiV1CartsMyCartItemsByItemIdResponse = DeleteApiV1CartsMyCartItemsByItemIdResponses[keyof DeleteApiV1CartsMyCartItemsByItemIdResponses];

export type DeleteApiV1CartsMyCartPromocodeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/carts/my-cart/promocode';
};

export type DeleteApiV1CartsMyCartPromocodeResponses = {
    /**
     * OK
     */
    200: GuidResult;
};

export type DeleteApiV1CartsMyCartPromocodeResponse = DeleteApiV1CartsMyCartPromocodeResponses[keyof DeleteApiV1CartsMyCartPromocodeResponses];

export type PostApiV1CartsMyCartPromocodeData = {
    body?: ApplyPromocodeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/carts/my-cart/promocode';
};

export type PostApiV1CartsMyCartPromocodeResponses = {
    /**
     * OK
     */
    200: GuidResult;
};

export type PostApiV1CartsMyCartPromocodeResponse = PostApiV1CartsMyCartPromocodeResponses[keyof PostApiV1CartsMyCartPromocodeResponses];

export type GetApiCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type GetApiCompaniesResponses = {
    /**
     * OK
     */
    200: CompanyDtoListResult;
};

export type GetApiCompaniesResponse = GetApiCompaniesResponses[keyof GetApiCompaniesResponses];

export type PostApiCompaniesData = {
    body?: CreateCompanyCommand;
    path?: never;
    query?: never;
    url: '/api/companies';
};

export type PostApiCompaniesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PostApiCompaniesError = PostApiCompaniesErrors[keyof PostApiCompaniesErrors];

export type PostApiCompaniesResponses = {
    /**
     * Created
     */
    201: CompanyDtoResult;
};

export type PostApiCompaniesResponse = PostApiCompaniesResponses[keyof PostApiCompaniesResponses];

export type PutApiCompaniesReorderData = {
    body?: ReorderCompaniesCommand;
    path?: never;
    query?: never;
    url: '/api/companies/reorder';
};

export type PutApiCompaniesReorderErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type PutApiCompaniesReorderError = PutApiCompaniesReorderErrors[keyof PutApiCompaniesReorderErrors];

export type PutApiCompaniesReorderResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiCompaniesReorderResponse = PutApiCompaniesReorderResponses[keyof PutApiCompaniesReorderResponses];

export type DeleteApiCompaniesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type DeleteApiCompaniesByIdErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type DeleteApiCompaniesByIdError = DeleteApiCompaniesByIdErrors[keyof DeleteApiCompaniesByIdErrors];

export type DeleteApiCompaniesByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiCompaniesByIdResponse = DeleteApiCompaniesByIdResponses[keyof DeleteApiCompaniesByIdResponses];

export type PutApiCompaniesByIdData = {
    body?: UpdateCompanyRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/companies/{id}';
};

export type PutApiCompaniesByIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PutApiCompaniesByIdError = PutApiCompaniesByIdErrors[keyof PutApiCompaniesByIdErrors];

export type PutApiCompaniesByIdResponses = {
    /**
     * OK
     */
    200: CompanyDtoResult;
};

export type PutApiCompaniesByIdResponse = PutApiCompaniesByIdResponses[keyof PutApiCompaniesByIdResponses];

export type GetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsResponses = {
    /**
     * OK
     */
    200: DashboardStatsDtoResult;
};

export type GetStatsResponse = GetStatsResponses[keyof GetStatsResponses];

export type GetChartData = {
    body?: never;
    path?: never;
    query?: {
        year?: number;
        month?: number;
    };
    url: '/chart';
};

export type GetChartResponses = {
    /**
     * OK
     */
    200: DashboardChartDtoResult;
};

export type GetChartResponse = GetChartResponses[keyof GetChartResponses];

export type GetApiFamiliesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/families';
};

export type GetApiFamiliesResponses = {
    /**
     * OK
     */
    200: FamilyDtoListResult;
};

export type GetApiFamiliesResponse = GetApiFamiliesResponses[keyof GetApiFamiliesResponses];

export type PostApiFamiliesData = {
    body?: CreateFamilyCommand;
    path?: never;
    query?: never;
    url: '/api/families';
};

export type PostApiFamiliesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PostApiFamiliesError = PostApiFamiliesErrors[keyof PostApiFamiliesErrors];

export type PostApiFamiliesResponses = {
    /**
     * Created
     */
    201: FamilyDtoResult;
};

export type PostApiFamiliesResponse = PostApiFamiliesResponses[keyof PostApiFamiliesResponses];

export type PutApiFamiliesReorderData = {
    body?: ReorderFamiliesCommand;
    path?: never;
    query?: never;
    url: '/api/families/reorder';
};

export type PutApiFamiliesReorderErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type PutApiFamiliesReorderError = PutApiFamiliesReorderErrors[keyof PutApiFamiliesReorderErrors];

export type PutApiFamiliesReorderResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiFamiliesReorderResponse = PutApiFamiliesReorderResponses[keyof PutApiFamiliesReorderResponses];

export type DeleteApiFamiliesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/families/{id}';
};

export type DeleteApiFamiliesByIdErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type DeleteApiFamiliesByIdError = DeleteApiFamiliesByIdErrors[keyof DeleteApiFamiliesByIdErrors];

export type DeleteApiFamiliesByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiFamiliesByIdResponse = DeleteApiFamiliesByIdResponses[keyof DeleteApiFamiliesByIdResponses];

export type PutApiFamiliesByIdData = {
    body?: UpdateFamilyRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/families/{id}';
};

export type PutApiFamiliesByIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
    /**
     * Conflict
     */
    409: ObjectResult;
};

export type PutApiFamiliesByIdError = PutApiFamiliesByIdErrors[keyof PutApiFamiliesByIdErrors];

export type PutApiFamiliesByIdResponses = {
    /**
     * OK
     */
    200: FamilyDtoResult;
};

export type PutApiFamiliesByIdResponse = PutApiFamiliesByIdResponses[keyof PutApiFamiliesByIdResponses];

export type GetApiLicensesData = {
    body?: never;
    path?: never;
    query?: {
        productId?: string;
        isActive?: boolean;
    };
    url: '/api/licenses';
};

export type GetApiLicensesResponses = {
    /**
     * OK
     */
    200: LicenseDtoListResult;
};

export type GetApiLicensesResponse = GetApiLicensesResponses[keyof GetApiLicensesResponses];

export type PostApiLicensesData = {
    body?: CreateLicenseCommand;
    path?: never;
    query?: never;
    url: '/api/licenses';
};

export type PostApiLicensesResponses = {
    /**
     * Created
     */
    201: LicenseDtoResult;
};

export type PostApiLicensesResponse = PostApiLicensesResponses[keyof PostApiLicensesResponses];

export type DeleteApiLicensesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}';
};

export type DeleteApiLicensesByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiLicensesByIdResponse = DeleteApiLicensesByIdResponses[keyof DeleteApiLicensesByIdResponses];

export type GetApiLicensesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}';
};

export type GetApiLicensesByIdResponses = {
    /**
     * OK
     */
    200: LicenseDtoResult;
};

export type GetApiLicensesByIdResponse = GetApiLicensesByIdResponses[keyof GetApiLicensesByIdResponses];

export type PutApiLicensesByIdData = {
    body?: UpdateLicenseCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}';
};

export type PutApiLicensesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesClientsByClientIdResetData = {
    body?: ResetLicenseHwidRequest;
    path: {
        clientId: string;
    };
    query?: never;
    url: '/api/licenses/clients/{clientId}/reset';
};

export type PostApiLicensesClientsByClientIdResetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesAdminByIdMigrateData = {
    body?: AdminMigrateLicenseRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/migrate';
};

export type PostApiLicensesAdminByIdMigrateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesByIdRenewData = {
    body?: RenewLicenseRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/{id}/renew';
};

export type PostApiLicensesByIdRenewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesAdminByIdRevokeData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/revoke';
};

export type PostApiLicensesAdminByIdRevokeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLicensesAdminByIdActivateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/activate';
};

export type PostApiLicensesAdminByIdActivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLicensesAdminByIdHwidsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/hwids';
};

export type GetApiLicensesAdminByIdHwidsResponses = {
    /**
     * OK
     */
    200: GetLicenseHwidsResponseResult;
};

export type GetApiLicensesAdminByIdHwidsResponse = GetApiLicensesAdminByIdHwidsResponses[keyof GetApiLicensesAdminByIdHwidsResponses];

export type PostApiLicensesAdminByIdHwidsData = {
    body?: AddHwidRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/hwids';
};

export type PostApiLicensesAdminByIdHwidsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiLicensesAdminByIdHwidsByHwidData = {
    body?: never;
    path: {
        id: string;
        hwid: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/hwids/{hwid}';
};

export type DeleteApiLicensesAdminByIdHwidsByHwidResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLicensesAdminByIdDiagnosticData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/licenses/admin/{id}/diagnostic';
};

export type GetApiLicensesAdminByIdDiagnosticResponses = {
    /**
     * OK
     */
    200: GetLicenseDiagnosticResponseResult;
};

export type GetApiLicensesAdminByIdDiagnosticResponse = GetApiLicensesAdminByIdDiagnosticResponses[keyof GetApiLicensesAdminByIdDiagnosticResponses];

export type GetApiPackagesData = {
    body?: never;
    path?: never;
    query?: {
        includeHidden?: boolean;
    };
    url: '/api/packages';
};

export type GetApiPackagesResponses = {
    /**
     * OK
     */
    200: PackageDtoListResult;
};

export type GetApiPackagesResponse = GetApiPackagesResponses[keyof GetApiPackagesResponses];

export type PostApiPackagesData = {
    body?: CreatePackageCommand;
    path?: never;
    query?: never;
    url: '/api/packages';
};

export type PostApiPackagesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type PostApiPackagesError = PostApiPackagesErrors[keyof PostApiPackagesErrors];

export type PostApiPackagesResponses = {
    /**
     * Created
     */
    201: GuidResult;
};

export type PostApiPackagesResponse = PostApiPackagesResponses[keyof PostApiPackagesResponses];

export type DeleteApiPackagesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/packages/{id}';
};

export type DeleteApiPackagesByIdErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiPackagesByIdError = DeleteApiPackagesByIdErrors[keyof DeleteApiPackagesByIdErrors];

export type DeleteApiPackagesByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiPackagesByIdResponse = DeleteApiPackagesByIdResponses[keyof DeleteApiPackagesByIdResponses];

export type GetApiPackagesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/packages/{id}';
};

export type GetApiPackagesByIdErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetApiPackagesByIdError = GetApiPackagesByIdErrors[keyof GetApiPackagesByIdErrors];

export type GetApiPackagesByIdResponses = {
    /**
     * OK
     */
    200: PackageDtoResult;
};

export type GetApiPackagesByIdResponse = GetApiPackagesByIdResponses[keyof GetApiPackagesByIdResponses];

export type PutApiPackagesByIdData = {
    body?: UpdatePackageRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/packages/{id}';
};

export type PutApiPackagesByIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiPackagesByIdError = PutApiPackagesByIdErrors[keyof PutApiPackagesByIdErrors];

export type PutApiPackagesByIdResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiPackagesByIdResponse = PutApiPackagesByIdResponses[keyof PutApiPackagesByIdResponses];

export type PutApiPackagesReorderData = {
    body?: ReorderPackagesCommand;
    path?: never;
    query?: never;
    url: '/api/packages/reorder';
};

export type PutApiPackagesReorderErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiPackagesReorderError = PutApiPackagesReorderErrors[keyof PutApiPackagesReorderErrors];

export type PutApiPackagesReorderResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiPackagesReorderResponse = PutApiPackagesReorderResponses[keyof PutApiPackagesReorderResponses];

export type PatchApiPackagesByIdHiddenData = {
    body?: SetPackageHiddenRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/packages/{id}/hidden';
};

export type PatchApiPackagesByIdHiddenErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PatchApiPackagesByIdHiddenError = PatchApiPackagesByIdHiddenErrors[keyof PatchApiPackagesByIdHiddenErrors];

export type PatchApiPackagesByIdHiddenResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PatchApiPackagesByIdHiddenResponse = PatchApiPackagesByIdHiddenResponses[keyof PatchApiPackagesByIdHiddenResponses];

export type DeleteApiPackagesByIdImageData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/packages/{id}/image';
};

export type DeleteApiPackagesByIdImageErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiPackagesByIdImageError = DeleteApiPackagesByIdImageErrors[keyof DeleteApiPackagesByIdImageErrors];

export type DeleteApiPackagesByIdImageResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiPackagesByIdImageResponse = DeleteApiPackagesByIdImageResponses[keyof DeleteApiPackagesByIdImageResponses];

export type PutApiPackagesByIdImageData = {
    body?: {
        File?: Blob | File;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/packages/{id}/image';
};

export type PutApiPackagesByIdImageErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiPackagesByIdImageError = PutApiPackagesByIdImageErrors[keyof PutApiPackagesByIdImageErrors];

export type PutApiPackagesByIdImageResponses = {
    /**
     * OK
     */
    200: StringResult;
};

export type PutApiPackagesByIdImageResponse = PutApiPackagesByIdImageResponses[keyof PutApiPackagesByIdImageResponses];

export type PostApiPaymentsCheckoutData = {
    /**
     * The payment checkout details. AmountInMinorUnits/ReferenceCode/Currency are recomputed server-side from the cart.
     */
    body?: PaymentCheckoutSessionRequest;
    path?: never;
    query?: never;
    url: '/api/payments/checkout';
};

export type PostApiPaymentsCheckoutErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Internal Server Error
     */
    500: ObjectResult;
};

export type PostApiPaymentsCheckoutError = PostApiPaymentsCheckoutErrors[keyof PostApiPaymentsCheckoutErrors];

export type PostApiPaymentsCheckoutResponses = {
    /**
     * OK
     */
    200: PaymentCheckoutStartResponseResult;
};

export type PostApiPaymentsCheckoutResponse = PostApiPaymentsCheckoutResponses[keyof PostApiPaymentsCheckoutResponses];

export type PostApiPaymentsRenewByLicenseIdCheckoutData = {
    /**
     * The payment checkout details. `ResourceId` is the PayablePrice id to renew with; AmountInMinorUnits/ReferenceCode/Currency
     * are recomputed server-side from that price.
     */
    body?: PaymentCheckoutSessionRequest;
    path: {
        /**
         * The License id to renew.
         */
        licenseId: string;
    };
    query?: never;
    url: '/api/payments/renew/{licenseId}/checkout';
};

export type PostApiPaymentsRenewByLicenseIdCheckoutErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Internal Server Error
     */
    500: ObjectResult;
};

export type PostApiPaymentsRenewByLicenseIdCheckoutError = PostApiPaymentsRenewByLicenseIdCheckoutErrors[keyof PostApiPaymentsRenewByLicenseIdCheckoutErrors];

export type PostApiPaymentsRenewByLicenseIdCheckoutResponses = {
    /**
     * OK
     */
    200: PaymentCheckoutStartResponseResult;
};

export type PostApiPaymentsRenewByLicenseIdCheckoutResponse = PostApiPaymentsRenewByLicenseIdCheckoutResponses[keyof PostApiPaymentsRenewByLicenseIdCheckoutResponses];

export type GetApiPaymentsByIdData = {
    body?: never;
    path: {
        /**
         * The Payment id.
         */
        id: string;
    };
    query?: never;
    url: '/api/payments/{id}';
};

export type GetApiPaymentsByIdErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetApiPaymentsByIdError = GetApiPaymentsByIdErrors[keyof GetApiPaymentsByIdErrors];

export type GetApiPaymentsByIdResponses = {
    /**
     * OK
     */
    200: PaymentStatusDtoResult;
};

export type GetApiPaymentsByIdResponse = GetApiPaymentsByIdResponses[keyof GetApiPaymentsByIdResponses];

export type PostApiPaymobWebhookData = {
    /**
     * The raw JSON payload from Paymob.
     */
    body?: unknown;
    path?: never;
    query?: {
        /**
         * The HMAC signature provided by Paymob in the query string.
         */
        hmac?: string;
    };
    url: '/api/paymob/webhook';
};

export type PostApiPaymobWebhookErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type PostApiPaymobWebhookError = PostApiPaymobWebhookErrors[keyof PostApiPaymobWebhookErrors];

export type PostApiPaymobWebhookResponses = {
    /**
     * OK
     */
    200: PaymentWebhookParseResultResult;
};

export type PostApiPaymobWebhookResponse = PostApiPaymobWebhookResponses[keyof PostApiPaymobWebhookResponses];

export type GetApiProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If true, includes hidden products in the response. Default is false.
         */
        includeHidden?: boolean;
        companyId?: string;
    };
    url: '/api/products';
};

export type GetApiProductsResponses = {
    /**
     * OK
     */
    200: ProductDtoListResult;
};

export type GetApiProductsResponse = GetApiProductsResponses[keyof GetApiProductsResponses];

export type PostApiProductsData = {
    /**
     * The details required to create the product.
     */
    body?: CreateProductCommand;
    path?: never;
    query?: never;
    url: '/api/products';
};

export type PostApiProductsErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type PostApiProductsError = PostApiProductsErrors[keyof PostApiProductsErrors];

export type PostApiProductsResponses = {
    /**
     * Created
     */
    201: ProductDtoResult;
};

export type PostApiProductsResponse = PostApiProductsResponses[keyof PostApiProductsResponses];

export type DeleteApiProductsByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product to delete.
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type DeleteApiProductsByIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiProductsByIdError = DeleteApiProductsByIdErrors[keyof DeleteApiProductsByIdErrors];

export type DeleteApiProductsByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsByIdResponse = DeleteApiProductsByIdResponses[keyof DeleteApiProductsByIdResponses];

export type GetApiProductsByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product.
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type GetApiProductsByIdErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetApiProductsByIdError = GetApiProductsByIdErrors[keyof GetApiProductsByIdErrors];

export type GetApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDtoResult;
};

export type GetApiProductsByIdResponse = GetApiProductsByIdResponses[keyof GetApiProductsByIdResponses];

export type PutApiProductsByIdData = {
    /**
     * The product details to update.
     */
    body?: UpdateProductCommand;
    path: {
        /**
         * The unique identifier of the product.
         */
        id: string;
    };
    query?: never;
    url: '/api/products/{id}';
};

export type PutApiProductsByIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiProductsByIdError = PutApiProductsByIdErrors[keyof PutApiProductsByIdErrors];

export type PutApiProductsByIdResponses = {
    /**
     * OK
     */
    200: ProductDtoResult;
};

export type PutApiProductsByIdResponse = PutApiProductsByIdResponses[keyof PutApiProductsByIdResponses];

export type GetApiProductsByParentIdChildrenData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the parent product.
         */
        parentId: string;
    };
    query?: never;
    url: '/api/products/{parentId}/children';
};

export type GetApiProductsByParentIdChildrenErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type GetApiProductsByParentIdChildrenError = GetApiProductsByParentIdChildrenErrors[keyof GetApiProductsByParentIdChildrenErrors];

export type GetApiProductsByParentIdChildrenResponses = {
    /**
     * OK
     */
    200: ProductDtoListResult;
};

export type GetApiProductsByParentIdChildrenResponse = GetApiProductsByParentIdChildrenResponses[keyof GetApiProductsByParentIdChildrenResponses];

export type PostApiProductsByParentIdChildrenData = {
    /**
     * The details required to create the child product.
     */
    body?: CreateChildProductRequest;
    path: {
        /**
         * The unique identifier of the parent product.
         */
        parentId: string;
    };
    query?: never;
    url: '/api/products/{parentId}/children';
};

export type PostApiProductsByParentIdChildrenErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type PostApiProductsByParentIdChildrenError = PostApiProductsByParentIdChildrenErrors[keyof PostApiProductsByParentIdChildrenErrors];

export type PostApiProductsByParentIdChildrenResponses = {
    /**
     * Created
     */
    201: ProductDtoResult;
};

export type PostApiProductsByParentIdChildrenResponse = PostApiProductsByParentIdChildrenResponses[keyof PostApiProductsByParentIdChildrenResponses];

export type PutApiProductsReorderData = {
    body?: ReorderProductsCommand;
    path?: never;
    query?: never;
    url: '/api/products/reorder';
};

export type PutApiProductsReorderErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type PutApiProductsReorderError = PutApiProductsReorderErrors[keyof PutApiProductsReorderErrors];

export type PutApiProductsReorderResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiProductsReorderResponse = PutApiProductsReorderResponses[keyof PutApiProductsReorderResponses];

export type GetApiProductsByProductIdMediaData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media';
};

export type GetApiProductsByProductIdMediaErrors = {
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetApiProductsByProductIdMediaError = GetApiProductsByProductIdMediaErrors[keyof GetApiProductsByProductIdMediaErrors];

export type GetApiProductsByProductIdMediaResponses = {
    /**
     * OK
     */
    200: ProductMediaDtoListResult;
};

export type GetApiProductsByProductIdMediaResponse = GetApiProductsByProductIdMediaResponses[keyof GetApiProductsByProductIdMediaResponses];

export type PostApiProductsByProductIdMediaData = {
    body?: {
        File?: Blob | File;
        Order?: number;
    };
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media';
};

export type PostApiProductsByProductIdMediaErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PostApiProductsByProductIdMediaError = PostApiProductsByProductIdMediaErrors[keyof PostApiProductsByProductIdMediaErrors];

export type PostApiProductsByProductIdMediaResponses = {
    /**
     * Created
     */
    201: ProductMediaDtoResult;
};

export type PostApiProductsByProductIdMediaResponse = PostApiProductsByProductIdMediaResponses[keyof PostApiProductsByProductIdMediaResponses];

export type PostApiProductsByProductIdMediaUrlData = {
    /**
     * The media URL details.
     */
    body?: ProductMediaRequest;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media/url';
};

export type PostApiProductsByProductIdMediaUrlErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PostApiProductsByProductIdMediaUrlError = PostApiProductsByProductIdMediaUrlErrors[keyof PostApiProductsByProductIdMediaUrlErrors];

export type PostApiProductsByProductIdMediaUrlResponses = {
    /**
     * Created
     */
    201: ProductMediaDtoResult;
};

export type PostApiProductsByProductIdMediaUrlResponse = PostApiProductsByProductIdMediaUrlResponses[keyof PostApiProductsByProductIdMediaUrlResponses];

export type DeleteApiProductsByProductIdMediaByMediaIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
        /**
         * The unique identifier of the media item.
         */
        mediaId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media/{mediaId}';
};

export type DeleteApiProductsByProductIdMediaByMediaIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiProductsByProductIdMediaByMediaIdError = DeleteApiProductsByProductIdMediaByMediaIdErrors[keyof DeleteApiProductsByProductIdMediaByMediaIdErrors];

export type DeleteApiProductsByProductIdMediaByMediaIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsByProductIdMediaByMediaIdResponse = DeleteApiProductsByProductIdMediaByMediaIdResponses[keyof DeleteApiProductsByProductIdMediaByMediaIdResponses];

export type PutApiProductsByProductIdMediaByMediaIdData = {
    body?: {
        File?: Blob | File;
        Url?: string;
        Order?: number;
    };
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
        /**
         * The unique identifier of the media item.
         */
        mediaId: string;
    };
    query?: never;
    url: '/api/products/{productId}/media/{mediaId}';
};

export type PutApiProductsByProductIdMediaByMediaIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiProductsByProductIdMediaByMediaIdError = PutApiProductsByProductIdMediaByMediaIdErrors[keyof PutApiProductsByProductIdMediaByMediaIdErrors];

export type PutApiProductsByProductIdMediaByMediaIdResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiProductsByProductIdMediaByMediaIdResponse = PutApiProductsByProductIdMediaByMediaIdResponses[keyof PutApiProductsByProductIdMediaByMediaIdResponses];

export type PostApiProductsByProductIdFeaturesData = {
    /**
     * The feature details.
     */
    body?: ProductFeatureRequest;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/features';
};

export type PostApiProductsByProductIdFeaturesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PostApiProductsByProductIdFeaturesError = PostApiProductsByProductIdFeaturesErrors[keyof PostApiProductsByProductIdFeaturesErrors];

export type PostApiProductsByProductIdFeaturesResponses = {
    /**
     * Created
     */
    201: ProductFeatureDtoResult;
};

export type PostApiProductsByProductIdFeaturesResponse = PostApiProductsByProductIdFeaturesResponses[keyof PostApiProductsByProductIdFeaturesResponses];

export type DeleteApiProductsByProductIdFeaturesByFeatureIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
        /**
         * The unique identifier of the feature.
         */
        featureId: string;
    };
    query?: never;
    url: '/api/products/{productId}/features/{featureId}';
};

export type DeleteApiProductsByProductIdFeaturesByFeatureIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiProductsByProductIdFeaturesByFeatureIdError = DeleteApiProductsByProductIdFeaturesByFeatureIdErrors[keyof DeleteApiProductsByProductIdFeaturesByFeatureIdErrors];

export type DeleteApiProductsByProductIdFeaturesByFeatureIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsByProductIdFeaturesByFeatureIdResponse = DeleteApiProductsByProductIdFeaturesByFeatureIdResponses[keyof DeleteApiProductsByProductIdFeaturesByFeatureIdResponses];

export type PutApiProductsByProductIdFeaturesByFeatureIdData = {
    /**
     * The feature details to update.
     */
    body?: ProductFeatureRequest;
    path: {
        /**
         * The unique identifier of the product.
         */
        productId: string;
        /**
         * The unique identifier of the feature.
         */
        featureId: string;
    };
    query?: never;
    url: '/api/products/{productId}/features/{featureId}';
};

export type PutApiProductsByProductIdFeaturesByFeatureIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiProductsByProductIdFeaturesByFeatureIdError = PutApiProductsByProductIdFeaturesByFeatureIdErrors[keyof PutApiProductsByProductIdFeaturesByFeatureIdErrors];

export type PutApiProductsByProductIdFeaturesByFeatureIdResponses = {
    /**
     * OK
     */
    200: ProductFeatureDtoResult;
};

export type PutApiProductsByProductIdFeaturesByFeatureIdResponse = PutApiProductsByProductIdFeaturesByFeatureIdResponses[keyof PutApiProductsByProductIdFeaturesByFeatureIdResponses];

export type GetApiProductsByIdVersionsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        onlyActive?: boolean;
    };
    url: '/api/products/{id}/versions';
};

export type GetApiProductsByIdVersionsResponses = {
    /**
     * OK
     */
    200: ProductVersionDtoListResult;
};

export type GetApiProductsByIdVersionsResponse = GetApiProductsByIdVersionsResponses[keyof GetApiProductsByIdVersionsResponses];

export type PostApiProductsByIdVersionsData = {
    body?: {
        File?: Blob | File;
        VersionNumber?: string;
        ReleaseNotes?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/products/{id}/versions';
};

export type PostApiProductsByIdVersionsResponses = {
    /**
     * Created
     */
    201: ProductVersionDtoResult;
};

export type PostApiProductsByIdVersionsResponse = PostApiProductsByIdVersionsResponses[keyof PostApiProductsByIdVersionsResponses];

export type GetApiProductsByIdVersionsLatestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/products/{id}/versions/latest';
};

export type GetApiProductsByIdVersionsLatestResponses = {
    /**
     * OK
     */
    200: ProductVersionDtoResult;
};

export type GetApiProductsByIdVersionsLatestResponse = GetApiProductsByIdVersionsLatestResponses[keyof GetApiProductsByIdVersionsLatestResponses];

export type PutApiProductsByProductIdVersionsByVersionIdToggleStatusData = {
    body?: boolean;
    path: {
        productId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/products/{productId}/versions/{versionId}/toggle-status';
};

export type PutApiProductsByProductIdVersionsByVersionIdToggleStatusResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiProductsByProductIdVersionsByVersionIdToggleStatusResponse = PutApiProductsByProductIdVersionsByVersionIdToggleStatusResponses[keyof PutApiProductsByProductIdVersionsByVersionIdToggleStatusResponses];

export type DeleteApiProductsByProductIdVersionsByVersionIdData = {
    body?: never;
    path: {
        productId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/products/{productId}/versions/{versionId}';
};

export type DeleteApiProductsByProductIdVersionsByVersionIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsByProductIdVersionsByVersionIdResponse = DeleteApiProductsByProductIdVersionsByVersionIdResponses[keyof DeleteApiProductsByProductIdVersionsByVersionIdResponses];

export type GetApiProductsByProductIdVersionsByVersionIdDownloadData = {
    body?: never;
    path: {
        productId: string;
        versionId: string;
    };
    query?: never;
    url: '/api/products/{productId}/versions/{versionId}/download';
};

export type GetApiProductsByProductIdVersionsByVersionIdDownloadResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiProductsByProductIdOffersData = {
    body?: never;
    path: {
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/offers';
};

export type GetApiProductsByProductIdOffersResponses = {
    /**
     * OK
     */
    200: OfferDtoListResult;
};

export type GetApiProductsByProductIdOffersResponse = GetApiProductsByProductIdOffersResponses[keyof GetApiProductsByProductIdOffersResponses];

export type PostApiProductsByProductIdOffersData = {
    body?: CreateOfferCommand;
    path: {
        productId: string;
    };
    query?: never;
    url: '/api/products/{productId}/offers';
};

export type PostApiProductsByProductIdOffersResponses = {
    /**
     * Created
     */
    201: OfferDtoResult;
};

export type PostApiProductsByProductIdOffersResponse = PostApiProductsByProductIdOffersResponses[keyof PostApiProductsByProductIdOffersResponses];

export type DeleteApiProductsOffersByOfferIdData = {
    body?: never;
    path: {
        offerId: string;
    };
    query?: never;
    url: '/api/products/offers/{offerId}';
};

export type DeleteApiProductsOffersByOfferIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiProductsOffersByOfferIdResponse = DeleteApiProductsOffersByOfferIdResponses[keyof DeleteApiProductsOffersByOfferIdResponses];

export type PutApiProductsOffersByOfferIdData = {
    body?: UpdateOfferCommand;
    path: {
        offerId: string;
    };
    query?: never;
    url: '/api/products/offers/{offerId}';
};

export type PutApiProductsOffersByOfferIdResponses = {
    /**
     * OK
     */
    200: UpdatedResult;
};

export type PutApiProductsOffersByOfferIdResponse = PutApiProductsOffersByOfferIdResponses[keyof PutApiProductsOffersByOfferIdResponses];

export type GetApiPromocodesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * If true, includes hidden promocodes in the response. Default is false.
         */
        includeHidden?: boolean;
    };
    url: '/api/promocodes';
};

export type GetApiPromocodesErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type GetApiPromocodesError = GetApiPromocodesErrors[keyof GetApiPromocodesErrors];

export type GetApiPromocodesResponses = {
    /**
     * OK
     */
    200: PromocodeDtoListResult;
};

export type GetApiPromocodesResponse = GetApiPromocodesResponses[keyof GetApiPromocodesResponses];

export type PostApiPromocodesData = {
    /**
     * The details required to create the promocode (e.g., Code).
     */
    body?: CreatePromocodeCommand;
    path?: never;
    query?: never;
    url: '/api/promocodes';
};

export type PostApiPromocodesErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
};

export type PostApiPromocodesError = PostApiPromocodesErrors[keyof PostApiPromocodesErrors];

export type PostApiPromocodesResponses = {
    /**
     * Created
     */
    201: PromocodeDtoResult;
};

export type PostApiPromocodesResponse = PostApiPromocodesResponses[keyof PostApiPromocodesResponses];

export type DeleteApiPromocodesByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the promocode to delete.
         */
        id: string;
    };
    query?: never;
    url: '/api/promocodes/{id}';
};

export type DeleteApiPromocodesByIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type DeleteApiPromocodesByIdError = DeleteApiPromocodesByIdErrors[keyof DeleteApiPromocodesByIdErrors];

export type DeleteApiPromocodesByIdResponses = {
    /**
     * OK
     */
    200: DeletedResult;
};

export type DeleteApiPromocodesByIdResponse = DeleteApiPromocodesByIdResponses[keyof DeleteApiPromocodesByIdResponses];

export type GetApiPromocodesByIdData = {
    body?: never;
    path: {
        /**
         * The unique identifier of the promocode.
         */
        id: string;
    };
    query?: never;
    url: '/api/promocodes/{id}';
};

export type GetApiPromocodesByIdErrors = {
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type GetApiPromocodesByIdError = GetApiPromocodesByIdErrors[keyof GetApiPromocodesByIdErrors];

export type GetApiPromocodesByIdResponses = {
    /**
     * OK
     */
    200: PromocodeDtoResult;
};

export type GetApiPromocodesByIdResponse = GetApiPromocodesByIdResponses[keyof GetApiPromocodesByIdResponses];

export type PutApiPromocodesByIdData = {
    /**
     * The details to update.
     */
    body?: UpdatePromocodeCommand;
    path: {
        /**
         * The unique identifier of the promocode.
         */
        id: string;
    };
    query?: never;
    url: '/api/promocodes/{id}';
};

export type PutApiPromocodesByIdErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
    /**
     * Unauthorized
     */
    401: ObjectResult;
    /**
     * Forbidden
     */
    403: ObjectResult;
    /**
     * Not Found
     */
    404: ObjectResult;
};

export type PutApiPromocodesByIdError = PutApiPromocodesByIdErrors[keyof PutApiPromocodesByIdErrors];

export type PutApiPromocodesByIdResponses = {
    /**
     * OK
     */
    200: PromocodeDtoResult;
};

export type PutApiPromocodesByIdResponse = PutApiPromocodesByIdResponses[keyof PutApiPromocodesByIdResponses];

export type PostApiStripeWebhookData = {
    /**
     * The raw JSON payload from Stripe.
     */
    body?: unknown;
    path?: never;
    query?: never;
    url: '/api/stripe/webhook';
};

export type PostApiStripeWebhookErrors = {
    /**
     * Bad Request
     */
    400: ObjectResult;
};

export type PostApiStripeWebhookError = PostApiStripeWebhookErrors[keyof PostApiStripeWebhookErrors];

export type PostApiStripeWebhookResponses = {
    /**
     * OK
     */
    200: PaymentWebhookParseResultResult;
};

export type PostApiStripeWebhookResponse = PostApiStripeWebhookResponses[keyof PostApiStripeWebhookResponses];

export type GetApiTicketCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/ticket-categories';
};

export type GetApiTicketCategoriesResponses = {
    /**
     * OK
     */
    200: Array<TicketCategoryDto>;
};

export type GetApiTicketCategoriesResponse = GetApiTicketCategoriesResponses[keyof GetApiTicketCategoriesResponses];

export type PostApiTicketCategoriesData = {
    body?: CreateTicketCategoryCommand;
    path?: never;
    query?: never;
    url: '/api/ticket-categories';
};

export type PostApiTicketCategoriesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiTicketCategoriesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ticket-categories/{id}';
};

export type DeleteApiTicketCategoriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiTicketCategoriesByIdData = {
    body?: UpdateTicketCategoryCommand;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/ticket-categories/{id}';
};

export type PutApiTicketCategoriesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTicketsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
    };
    url: '/api/tickets';
};

export type GetApiTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTicketsData = {
    body?: CreateTicketRequest;
    path?: never;
    query?: never;
    url: '/api/tickets';
};

export type PostApiTicketsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTicketsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tickets/{id}';
};

export type GetApiTicketsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiTicketsByIdCommentsData = {
    body?: AddTicketCommentRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tickets/{id}/comments';
};

export type PostApiTicketsByIdCommentsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PutApiTicketsByIdStatusData = {
    body?: UpdateTicketStatusRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/tickets/{id}/status';
};

export type PutApiTicketsByIdStatusResponses = {
    /**
     * OK
     */
    200: unknown;
};
